export { default as Login } from './Auth/Login';
export { default as Register } from './Auth/Register';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Capital } from './Capital/Capital';
export { default as AnimalList } from './Animals/AnimalList';
export { default as AnimalForm } from './Animals/AnimalForm';
export { default as BulkUpload } from './Animals/BulkUpload';
export { default as MoveToPen } from './Animals/MoveToPen';
export { default as PenList } from './Pens/PenList';
export { default as PenForm } from './Pens/PenForm';
export { default as StockOverview } from './Stock/StockOverview';
export { default as StockMedicationList } from './Stock/StockMedicationList';
export { default as StockFeedingList } from './Stock/StockFeedingList';
export { default as StockAccessoryList } from './Stock/StockAccessoryList';
export { default as StockMedicationForm } from './Stock/StockMedicationForm';
export { default as StockFeedingForm } from './Stock/StockFeedingForm';
export { default as StockAccessoryForm } from './Stock/StockAccessoryForm';
export { default as StockMedicationBulkUpload } from './Stock/StockMedicationBulkUpload';
export { default as StockFeedingBulkUpload } from './Stock/StockFeedingBulkUpload';
export { default as StockEdit } from './Stock/StockEdit';
export { default as EmployeeList } from './Employees/EmployeeList';
export { default as EmployeeForm } from './Employees/EmployeeForm';
export { default as EmployeeAdvance } from './Employees/EmployeeAdvance';
// Health & Veterinary
export { default as Treatment } from './Health/Treatment';
export { default as CureTracking } from './Health/CureTracking';
export { default as Deworming } from './Health/Deworming';
export { default as BodyWeight } from './Health/BodyWeight';
export { default as BodyConditionScore } from './Health/BodyConditionScore';
export { default as HoofTrimming } from './Health/HoofTrimming';
// Feed & Recipe Management
export { default as FeedRecipeList } from './Feed/FeedRecipeList';
export { default as FeedRecipeForm } from './Feed/FeedRecipeForm';
export { default as ApplyRecipe } from './Feed/ApplyRecipe';
// Vaccination Management
export { default as VaccineList } from './Vaccination/VaccineList';
export { default as CreateVaccine } from './Vaccination/CreateVaccine';
export { default as ApplyVaccine } from './Vaccination/ApplyVaccine';
export { default as ApplicationHistory } from './Vaccination/ApplicationHistory';
